scoreboard objectives remove AFKCounter
scoreboard objectives remove AFKClock 
scoreboard objectives remove AFKMovement
scoreboard objectives remove AFKDisWalk 
scoreboard objectives remove AFKDisCrouch
scoreboard objectives remove AFKDisSprint
scoreboard objectives remove AFKDisSwum 
scoreboard objectives remove AFKDisFallen
scoreboard objectives remove AFKDisClimb
scoreboard objectives remove AFKDisFlown
scoreboard objectives remove AFKDisDove 
scoreboard objectives remove AFKDisBoat 
scoreboard objectives remove AFKDisPig 
scoreboard objectives remove AFKDisHorse 
scoreboard objectives remove AFKDisElytra 
scoreboard objectives remove AFKDisMinecart 
scoreboard objectives remove AFKTimesJumped 
scoreboard teams remove AFK